// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InnerStructB struct {
	Bool                 bool     `protobuf:"varint,1,opt,name=Bool,proto3" json:"Bool,omitempty"`
	Float64              float64  `protobuf:"fixed64,2,opt,name=Float64,proto3" json:"Float64,omitempty"`
	Int8                 int32    `protobuf:"varint,3,opt,name=Int8,proto3" json:"Int8,omitempty"`
	Uint64S              []uint64 `protobuf:"varint,4,rep,packed,name=Uint64s,proto3" json:"Uint64s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerStructB) Reset()         { *m = InnerStructB{} }
func (m *InnerStructB) String() string { return proto.CompactTextString(m) }
func (*InnerStructB) ProtoMessage()    {}
func (*InnerStructB) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_be9db850f74cd161, []int{0}
}
func (m *InnerStructB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerStructB.Unmarshal(m, b)
}
func (m *InnerStructB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerStructB.Marshal(b, m, deterministic)
}
func (dst *InnerStructB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerStructB.Merge(dst, src)
}
func (m *InnerStructB) XXX_Size() int {
	return xxx_messageInfo_InnerStructB.Size(m)
}
func (m *InnerStructB) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerStructB.DiscardUnknown(m)
}

var xxx_messageInfo_InnerStructB proto.InternalMessageInfo

func (m *InnerStructB) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *InnerStructB) GetFloat64() float64 {
	if m != nil {
		return m.Float64
	}
	return 0
}

func (m *InnerStructB) GetInt8() int32 {
	if m != nil {
		return m.Int8
	}
	return 0
}

func (m *InnerStructB) GetUint64S() []uint64 {
	if m != nil {
		return m.Uint64S
	}
	return nil
}

type Int32S struct {
	Ints                 []int32  `protobuf:"varint,1,rep,packed,name=ints,proto3" json:"ints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32S) Reset()         { *m = Int32S{} }
func (m *Int32S) String() string { return proto.CompactTextString(m) }
func (*Int32S) ProtoMessage()    {}
func (*Int32S) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_be9db850f74cd161, []int{1}
}
func (m *Int32S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32S.Unmarshal(m, b)
}
func (m *Int32S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32S.Marshal(b, m, deterministic)
}
func (dst *Int32S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32S.Merge(dst, src)
}
func (m *Int32S) XXX_Size() int {
	return xxx_messageInfo_Int32S.Size(m)
}
func (m *Int32S) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32S.DiscardUnknown(m)
}

var xxx_messageInfo_Int32S proto.InternalMessageInfo

func (m *Int32S) GetInts() []int32 {
	if m != nil {
		return m.Ints
	}
	return nil
}

type StructB struct {
	Str                  string             `protobuf:"bytes,1,opt,name=Str,proto3" json:"Str,omitempty"`
	Slice                []byte             `protobuf:"bytes,2,opt,name=Slice,proto3" json:"Slice,omitempty"`
	MapStrUint16         map[string]uint32  `protobuf:"bytes,3,rep,name=MapStrUint16,proto3" json:"MapStrUint16,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Inner                *InnerStructB      `protobuf:"bytes,4,opt,name=Inner,proto3" json:"Inner,omitempty"`
	Bt                   uint32             `protobuf:"varint,5,opt,name=Bt,proto3" json:"Bt,omitempty"`
	Int                  int32              `protobuf:"varint,6,opt,name=Int,proto3" json:"Int,omitempty"`
	Int64                int64              `protobuf:"varint,7,opt,name=Int64,proto3" json:"Int64,omitempty"`
	Strs                 []string           `protobuf:"bytes,8,rep,name=Strs,proto3" json:"Strs,omitempty"`
	SliceI64             []int64            `protobuf:"varint,9,rep,packed,name=SliceI64,proto3" json:"SliceI64,omitempty"`
	MapStrUint64         map[string]uint64  `protobuf:"bytes,10,rep,name=MapStrUint64,proto3" json:"MapStrUint64,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Recursive            []*StructB         `protobuf:"bytes,11,rep,name=Recursive,proto3" json:"Recursive,omitempty"`
	Float64              float64            `protobuf:"fixed64,12,opt,name=Float64,proto3" json:"Float64,omitempty"`
	MapStrSlice          map[string]*Int32S `protobuf:"bytes,13,rep,name=MapStrSlice,proto3" json:"MapStrSlice,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	F32                  float32            `protobuf:"fixed32,14,opt,name=F32,proto3" json:"F32,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StructB) Reset()         { *m = StructB{} }
func (m *StructB) String() string { return proto.CompactTextString(m) }
func (*StructB) ProtoMessage()    {}
func (*StructB) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_be9db850f74cd161, []int{2}
}
func (m *StructB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructB.Unmarshal(m, b)
}
func (m *StructB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructB.Marshal(b, m, deterministic)
}
func (dst *StructB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructB.Merge(dst, src)
}
func (m *StructB) XXX_Size() int {
	return xxx_messageInfo_StructB.Size(m)
}
func (m *StructB) XXX_DiscardUnknown() {
	xxx_messageInfo_StructB.DiscardUnknown(m)
}

var xxx_messageInfo_StructB proto.InternalMessageInfo

func (m *StructB) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *StructB) GetSlice() []byte {
	if m != nil {
		return m.Slice
	}
	return nil
}

func (m *StructB) GetMapStrUint16() map[string]uint32 {
	if m != nil {
		return m.MapStrUint16
	}
	return nil
}

func (m *StructB) GetInner() *InnerStructB {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *StructB) GetBt() uint32 {
	if m != nil {
		return m.Bt
	}
	return 0
}

func (m *StructB) GetInt() int32 {
	if m != nil {
		return m.Int
	}
	return 0
}

func (m *StructB) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *StructB) GetStrs() []string {
	if m != nil {
		return m.Strs
	}
	return nil
}

func (m *StructB) GetSliceI64() []int64 {
	if m != nil {
		return m.SliceI64
	}
	return nil
}

func (m *StructB) GetMapStrUint64() map[string]uint64 {
	if m != nil {
		return m.MapStrUint64
	}
	return nil
}

func (m *StructB) GetRecursive() []*StructB {
	if m != nil {
		return m.Recursive
	}
	return nil
}

func (m *StructB) GetFloat64() float64 {
	if m != nil {
		return m.Float64
	}
	return 0
}

func (m *StructB) GetMapStrSlice() map[string]*Int32S {
	if m != nil {
		return m.MapStrSlice
	}
	return nil
}

func (m *StructB) GetF32() float32 {
	if m != nil {
		return m.F32
	}
	return 0
}

func init() {
	proto.RegisterType((*InnerStructB)(nil), "InnerStructB")
	proto.RegisterType((*Int32S)(nil), "Int32s")
	proto.RegisterType((*StructB)(nil), "StructB")
	proto.RegisterMapType((map[string]*Int32S)(nil), "StructB.MapStrSliceEntry")
	proto.RegisterMapType((map[string]uint32)(nil), "StructB.MapStrUint16Entry")
	proto.RegisterMapType((map[string]uint64)(nil), "StructB.MapStrUint64Entry")
}

func init() { proto.RegisterFile("protobuf.proto", fileDescriptor_protobuf_be9db850f74cd161) }

var fileDescriptor_protobuf_be9db850f74cd161 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0xa5, 0xd3, 0xc9, 0x7c, 0x54, 0x66, 0x86, 0xb5, 0xf1, 0xd0, 0x0e, 0x0a, 0xcd, 0x08, 0xd2,
	0xa7, 0x80, 0x99, 0x10, 0x16, 0x05, 0x85, 0x80, 0x2b, 0x39, 0x78, 0xa9, 0xe0, 0xc5, 0xdb, 0xec,
	0x10, 0x21, 0xee, 0xd8, 0x59, 0x92, 0x9e, 0x85, 0xf9, 0x2b, 0xfe, 0x5a, 0xa9, 0xee, 0x8d, 0x66,
	0x76, 0x95, 0xbd, 0xbd, 0xa2, 0xea, 0xbd, 0x7e, 0xaf, 0x2a, 0x81, 0xd5, 0x6d, 0xd7, 0xda, 0xf6,
	0xfa, 0xf8, 0x3d, 0x71, 0x60, 0xf3, 0x03, 0x16, 0xa5, 0x31, 0x75, 0x57, 0xd9, 0xee, 0xb8, 0xb7,
	0x85, 0x10, 0x10, 0x16, 0x6d, 0x7b, 0x90, 0x4c, 0x31, 0x3d, 0x43, 0x87, 0x85, 0x84, 0xe9, 0xd5,
	0xa1, 0xdd, 0xd9, 0x3c, 0x93, 0x81, 0x62, 0x9a, 0xe1, 0x50, 0xd2, 0x74, 0x69, 0xec, 0xa5, 0xe4,
	0x8a, 0xe9, 0x08, 0x1d, 0xa6, 0xe9, 0xaf, 0x8d, 0xb1, 0x79, 0xd6, 0xcb, 0x50, 0x71, 0x1d, 0xe2,
	0x50, 0x6e, 0x5e, 0xc2, 0xa4, 0x34, 0x76, 0x9b, 0xf6, 0xc4, 0x6b, 0x8c, 0xed, 0x25, 0x53, 0x9c,
	0x78, 0x84, 0x37, 0xbf, 0x22, 0x98, 0x0e, 0x2e, 0x2e, 0x80, 0x57, 0xb6, 0x73, 0x26, 0xe6, 0x48,
	0x50, 0x3c, 0x87, 0xa8, 0x3a, 0x34, 0xfb, 0xda, 0x39, 0x58, 0xa0, 0x2f, 0xc4, 0x07, 0x58, 0x7c,
	0xd9, 0xdd, 0x56, 0xb6, 0xa3, 0x27, 0xde, 0xe6, 0x92, 0x2b, 0xae, 0xe3, 0x74, 0x9d, 0xdc, 0xeb,
	0x24, 0xe3, 0xe6, 0x27, 0x63, 0xbb, 0x13, 0x9e, 0xcd, 0x8b, 0xd7, 0x10, 0xb9, 0xf4, 0x32, 0x54,
	0x4c, 0xc7, 0xe9, 0x32, 0x19, 0xef, 0x02, 0x7d, 0x4f, 0xac, 0x20, 0x28, 0xac, 0x8c, 0x14, 0xd3,
	0x4b, 0x0c, 0x0a, 0x4b, 0xe6, 0x4a, 0x63, 0xe5, 0xc4, 0x65, 0x26, 0x48, 0xe6, 0x4a, 0x8a, 0x28,
	0xa7, 0x8a, 0x69, 0x8e, 0xbe, 0xa0, 0x90, 0x95, 0xed, 0x7a, 0x39, 0x53, 0x5c, 0xcf, 0xd1, 0x61,
	0xb1, 0x86, 0x99, 0x73, 0x5e, 0xe6, 0x99, 0x9c, 0x2b, 0xae, 0x39, 0xfe, 0xa9, 0xcf, 0xc3, 0xe4,
	0x99, 0x84, 0xff, 0x86, 0xc9, 0xb3, 0x47, 0x61, 0xf2, 0x4c, 0xbc, 0x81, 0x39, 0xd6, 0xfb, 0x63,
	0xd7, 0x37, 0x77, 0xb5, 0x8c, 0x1d, 0x79, 0x36, 0x90, 0xf1, 0x6f, 0x6b, 0x7c, 0xce, 0xc5, 0xf9,
	0x39, 0xdf, 0x43, 0xec, 0x15, 0xfd, 0xaa, 0x97, 0x4e, 0xe3, 0xc5, 0x03, 0x03, 0xae, 0xe7, 0xdf,
	0x1f, 0x4f, 0xd3, 0x5a, 0xae, 0xb6, 0xa9, 0x5c, 0x29, 0xa6, 0x03, 0x24, 0xb8, 0xfe, 0x08, 0xcf,
	0x1e, 0x1d, 0x80, 0xc6, 0x6e, 0xea, 0xd3, 0x70, 0xda, 0x9b, 0xfa, 0x44, 0xdb, 0xbb, 0xdb, 0x1d,
	0x8e, 0xfe, 0xb4, 0x4b, 0xf4, 0xc5, 0xbb, 0xe0, 0x92, 0x9d, 0x0b, 0xdc, 0x87, 0x7e, 0x4a, 0x20,
	0x1c, 0x0b, 0x7c, 0x86, 0x8b, 0x87, 0xa6, 0xff, 0xc1, 0x7f, 0x35, 0xe6, 0xc7, 0xe9, 0x34, 0xf1,
	0x5f, 0xe9, 0x48, 0xa8, 0x98, 0x7c, 0x0b, 0x7f, 0xee, 0x1a, 0x73, 0x3d, 0x71, 0x7f, 0xcd, 0xf6,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xe1, 0x28, 0x0d, 0x47, 0x03, 0x00, 0x00,
}
